name: Backend CI/CD

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "623234912973"
  ECR_REPO: backenddocker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      # 3. Login to Amazon ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login \
            --username AWS \
            --password-stdin \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4. Create Docker image tag
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 5. Build Docker image
      - name: Build Docker Image
        working-directory: backend
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG $IMAGE_URI

      # 6. Push Docker image to ECR
      - name: Push Image to ECR
        run: |
          docker push $IMAGE_URI

      # 7. Display image information
      - name: Show Image
        run: |
          echo "Docker image pushed successfully:"
          echo "$IMAGE_URI"
